pipeline {
  agent any

  tools {nodejs "nodejs"}

  stages {
    stage('INSTALL PACKAGES') {
      steps {
        sh "npm install"
      }
    }
     stage('Reporting') {
      steps {
        echo "start building lighthouse"
         sh "npm run start:light"
      }
    }
    stage('BUILD APP') {
      steps {
        sh "node_modules/.bin/ng build --prod"
      }
    }
     
  }
}