pipeline {
  agent any

  tools {nodejs "nodejs"}

  stages {
    stage('INSTALL PACKAGES') {
      steps {
        sh "npm install"
      }
    }
    //  stage('Reporting') {
    //   steps {
    //     echo "start building lighthouse"
    //      echo "${JENKINS_HOME}"
    //      sh "node ${JENKINS_HOME}/workspace/automation1/src/lightHouse/index.js"
    //   }
    // }
    stage('BUILD APP') {
      steps {
        sh "node_modules/.bin/ng build --prod"
      }
    }
     
  }
}

// workspace/automation1/src/lightHouse$
// /var/jenkins_home/workspace/automation1/src/lighthouse/index.js
// ./src/lighthouse/index.js